export type Language = "fr" | "ar";

export const common = {
  phone: "+216 71 840 210",
  phoneRaw: "+21671840210",
  whatsapp: "+216 98 420 530",
  whatsappRaw: "21698420530",
  email: "contact@chaabani-adoul.tn",
  mapsUrl: "https://www.google.com/maps/search/?api=1&query=Centre+Urbain+Nord+Tunis",
};

export const copy = {
  fr: {
    lang: "fr-FR",
    dir: "ltr" as const,
    switchLabel: "العربية",
    eyebrow: "CABINET D'ADoul ECHHAD",
    brandName: "Abderrazak Chaabani",
    role: "Adoul Echhad",
    roleAr: "عدل إشهاد",
    location: "Tunis, Tunisie",
    nav: ["Accueil", "À propos", "Services", "Méthode", "Contact"],
    hero: {
      kicker: "Cabinet d'Adoul Echhad",
      title: "Votre accompagnement professionnel, avec rigueur et confiance.",
      body: "Rédaction, authentification et conservation des actes civils, immobiliers et successoraux, dans un cadre clair, confidentiel et professionnel.",
      primary: "Prendre rendez-vous",
      secondary: "Découvrir le cabinet",
      note: "Réception sur rendez-vous · Tunis",
      portraitLabel: "Cabinet d'Adoul Echhad",
    },
    about: {
      kicker: "Le cabinet",
      title: "Une pratique fondée sur la précision et l'écoute.",
      body: "Maître Abderrazak Chaabani accompagne les particuliers et les familles dans la préparation et la formalisation de leurs actes. Chaque demande est étudiée avec attention, expliquée avec clarté et traitée dans le respect de la confidentialité.",
      identity: "Abderrazak Chaabani",
      identityRole: "Adoul Echhad · Tunis",
      rows: [
        ["Fonction", "Adoul Echhad"],
        ["Localisation", "Tunis, Tunisie"],
        ["Langues", "Arabe · Français"],
        ["Réception", "Sur rendez-vous"],
      ],
    },
    values: [
      ["01", "Rigueur", "Une attention constante portée aux formes, aux pièces et aux détails."],
      ["02", "Confidentialité", "Des échanges discrets et un cadre respectueux pour chaque dossier."],
      ["03", "Clarté", "Des démarches expliquées simplement, étape par étape."],
      ["04", "Proximité", "Un interlocuteur accessible pour vous accompagner avec attention."],
    ],
    services: {
      kicker: "Domaines d'intervention",
      title: "Des actes préparés avec méthode.",
      body: "Une présentation claire des principaux domaines du cabinet. Le contenu peut être ajusté selon les prestations effectivement proposées.",
      items: [
        [
          "Actes et contrats",
          "Rédaction et formalisation des actes authentiques et contractuels.",
          "Le cabinet prépare et authentifie les conventions qui engagent les parties : contrats de vente, conventions préalables, engagements et clauses expresses. Chaque acte est relu, expliqué en amont et conservé dans un registre sécurisé, afin d'en garantir la date, l'authenticité et la force probante.",
        ],
        [
          "Actes relatifs aux biens",
          "Accompagnement des transactions et démarches relatives aux biens.",
          "Vente, échange, partage ou constitution de droits réels sur un immeuble ou un fonds de commerce : le cabinet vérifie les titres de propriété, les situations hypothécaires et les autorisations requises avant toute signature, puis accompagne les parties jusqu'au dépôt final.",
        ],
        [
          "Successions",
          "Préparation des actes et démarches liés aux successions et aux partages.",
          "Ouverture de la succession, établissement des actes de notoriété, calcul des parts selon les règles applicables et rédaction des actes de partage. Le cabinet coordonne les échanges entre héritiers avec impartialité, discrétion et pédagogie.",
        ],
        [
          "Affaires familiales",
          "Actes matrimoniaux, conventions familiales et démarches du statut personnel.",
          "Contrats de mariage, conventions de séparation de biens, reconnaissances et actes d'état civil : le cabinet accompagne les familles dans les moments décisifs, avec un souci constant de clarté sur les effets juridiques de chaque engagement.",
        ],
        [
          "Procurations et déclarations",
          "Procurations, déclarations et documents concernés.",
          "Procurations générales ou spéciales, déclarations, attestations et documents de représentation. Le cabinet rédige des actes précis, limités dans leur objet et leur durée, pour une utilisation sécurisée en Tunisie ou à l'étranger.",
        ],
        [
          "Autres prestations",
          "Dépôts, certifications et demandes particulières à préciser.",
          "Dépôts d'actes sous seing privé, certifications de signature, formalités d'enregistrement et demandes spécifiques. Pour toute prestation non listée, le cabinet vous répond dans les meilleurs délais.",
        ],
      ],
      action: "Demander un rendez-vous",
      detailLabel: "Description",
    },
    method: {
      kicker: "Notre méthode",
      title: "Un accompagnement en quatre temps.",
      items: [
        ["01", "Écouter", "Comprendre précisément votre besoin."],
        ["02", "Analyser", "Identifier les éléments et les pièces nécessaires."],
        ["03", "Préparer", "Organiser les démarches et préparer l'acte."],
        ["04", "Accompagner", "Assurer un suivi clair jusqu'à la finalisation."],
      ],
    },
    contact: {
      kicker: "Prendre contact",
      title: "Parlons de votre demande.",
      body: "Pour un rendez-vous ou une première information, le cabinet est à votre disposition.",
      address: "Centre Urbain Nord, Tunis",
      addressDetail: "Imm. Golden Towers · Bureau A-402",
      hours: "Lun – Ven · 08h30 – 17h30",
      whatsapp: "Contacter par WhatsApp",
      call: "Appeler le cabinet",
      formTitle: "Envoyer une demande",
      name: "Nom complet",
      phone: "Téléphone",
      email: "Email",
      subject: "Objet de la demande",
      message: "Votre message",
      placeholderName: "Votre nom",
      placeholderMessage: "Décrivez brièvement votre demande…",
      send: "Envoyer le message",
      success: "Votre demande est prête à être transmise.",
      successBody: "Vous pouvez l'envoyer directement par WhatsApp au cabinet.",
      newMessage: "Nouveau message",
      subjects: ["Actes et contrats", "Biens et immobilier", "Successions", "Affaires familiales", "Procurations", "Autre demande"],
    },
    footer: {
      line: "Un échange confidentiel, un accompagnement clair.",
      navigation: "Navigation",
      services: "Services",
      contact: "Contact",
      rights: "Officier public assermenté · Tous droits réservés.",
    },
  },
  ar: {
    lang: "ar-TN",
    dir: "rtl" as const,
    switchLabel: "Français",
    eyebrow: "مكتب عدل إشهاد",
    brandName: "عبد الرزاق شعباني",
    role: "عدل إشهاد",
    roleAr: "عدل إشهاد",
    location: "تونس، تونس",
    nav: ["الرئيسية", "من نحن", "الخدمات", "منهجيتنا", "اتصل بنا"],
    hero: {
      kicker: "مكتب عدل إشهاد",
      title: "مرافقة مهنية، بدقة وثقة.",
      body: "إعداد وتوثيق وحفظ الأوراق المدنية والعقارية والوصائية، في إطار واضح وسري ومهني.",
      primary: "طلب موعد",
      secondary: "اكتشف المكتب",
      note: "الاستقبال بموعد · تونس",
      portraitLabel: "مكتب عدل إشهاد",
    },
    about: {
      kicker: "المكتب",
      title: "ممارسة تقوم على الدقة والإصغاء.",
      body: "يرافق الأستاذ عبد الرزاق شعباني الأفراد والعائلات في إعداد وتوثيق أوراقهم. تُدرس كل مطالبة بعناية، وتُشرح بوضوح، وتُعالج في إطار يحترم السرية.",
      identity: "عبد الرزاق شعباني",
      identityRole: "عدل إشهاد · تونس",
      rows: [
        ["الوظيفة", "عدل إشهاد"],
        ["الموقع", "تونس، تونس"],
        ["اللغات", "العربية · الفرنسية"],
        ["الاستقبال", "بموعد"],
      ],
    },
    values: [
      ["01", "الدقة", "عناية دائمة بالأشكال والوثائق وجميع التفاصيل."],
      ["02", "السرية", "تبادل خاص وإطار يحترم خصوصية كل ملف."],
      ["03", "الوضوح", "شرح الإجراءات ببساطة، مرحلة بعد مرحلة."],
      ["04", "القرب", "مخاطب متاح لمرافقتكم بكل اهتمام."],
    ],
    services: {
      kicker: "مجالات التدخل",
      title: "أوراق تُحضّر بمنهجية.",
      body: "عرض واضح لأهم مجالات المكتب. يمكن تعديل المحتوى حسب الخدمات الفعلية المقترحة.",
      items: [
        [
          "العقود والاتفاقيات",
          "صياغة وتوثيق الأوراق الموثقة والعقدية.",
          "يُعِدّ المكتب ويوثّق الاتفاقيات الملزمة للطرفين: عقود البيع، الاتفاقات التمهيدية، الالتزامات والبنود الصريحة. تُراجع كل ورقة وتُشرح مسبقًا وتُحفظ في سجلّ آمن، بما يضمن تاريخها وصحتها وحجيّتها أمام القضاء.",
        ],
        [
          "الأوراق المتعلقة بالأملاك",
          "مرافقة التعاملات والإجراءات المتعلقة بالأملاك.",
          "بيع أو مقايضة أو تقسيم أو تكوين حقوق عينية على عقار أو محل تجاري: يتحقّق المكتب من طبيعة الملكية والرهون والأذونات المطلوبة قبل أي توقيع، ثم يرافق الأطراف إلى غاية إيداع الورقة النهائي.",
        ],
        [
          "الفرائض والميراث",
          "إعداد الأوراق والإجراءات المرتبطة بالوصايا والتقسيم.",
          "فتح الإرث، تحرير أوراق الإعلام، حساب الأنصبة وفق القواعد المعمول بها، وصياغة أوراق القسمة. ينسّق المكتب بين الورثة بحياد وسرّية، ويشرح لكل طرف حقوقه وواجباته بلغة واضحة.",
        ],
        [
          "الشؤون الأسرية",
          "الأوراق الزوجية والاتفاقيات العائلية.",
          "عقود الزواج، اتفاقيات فصل الأموال، الإقرارات وأوراق الحالة المدنية: يرافق المكتب العائلات في اللحظات الحاسمة، مع عناية دائمة بوضوح الآثار القانونية لكل التزام قبل التوقيع.",
        ],
        [
          "الوكالات والتصريحات",
          "الوكالات والتصريحات والوثائق ذات الصلة.",
          "الوكالات العامة أو الخاصة، التصريحات، الشهادات وأوراق التمثيل. يحرّر المكتب أوراقًا دقيقة، محدودة الموضوع والمدة، لاستعمال آمن داخل تونس أو خارجها، بما في ذلك التمثيل لدى الإدارات والمؤسسات.",
        ],
        [
          "خدمات أخرى",
          "الإيداعات والتصديقات والطلبات الخاصة.",
          "إيداع الأوراق العرفية، تصديقات التواقيع، إجراءات التسجيل والطلبات الخاصة. بالنسبة إلى أي خدمة غير مدرجة في هذه القائمة، يمكن الاتصال بالمكتب مباشرة للحصول على توضيح وتقدير مسبق.",
        ],
      ],
      action: "طلب موعد",
      detailLabel: "الوصف",
    },
    method: {
      kicker: "منهجيتنا",
      title: "مرافقة في أربع مراحل.",
      items: [
        ["01", "الإصغاء", "فهم حاجتكم بدقة."],
        ["02", "التحليل", "تحديد العناصر والوثائق اللازمة."],
        ["03", "الإعداد", "تنظيم الإجراءات وإعداد الورقة."],
        ["04", "المرافقة", "متابعة واضحة إلى غاية الإتمام."],
      ],
    },
    contact: {
      kicker: "اتصل بنا",
      title: "لنتحدث عن طلبكم.",
      body: "لموعد أو لاستفسار أولي، مكتب عدل الإشهاد على ذمتكم.",
      address: "النهضة الأولى، تونس",
      addressDetail: "برج غولدن تاور · مكتب 402",
      hours: "الاثنين – الجمعة · 08:30 – 17:30",
      whatsapp: "التواصل عبر واتساب",
      call: "الاتصال بالمكتب",
      formTitle: "إرسال طلب",
      name: "الاسم الكامل",
      phone: "الهاتف",
      email: "البريد الإلكتروني",
      subject: "موضوع الطلب",
      message: "رسالتكم",
      placeholderName: "اسمكم",
      placeholderMessage: "صفوا طلبكم بإيجاز…",
      send: "إرسال الرسالة",
      success: "طلبكم جاهز للإرسال.",
      successBody: "يمكنكم إرساله مباشرة عبر واتساب إلى المكتب.",
      newMessage: "رسالة جديدة",
      subjects: ["العقود والاتفاقيات", "الأملاك والعقارات", "الوصايا والفرائض", "الشؤون الأسرية", "الوكالات", "طلب آخر"],
    },
    footer: {
      line: "حوار سري، ومرافقة واضحة.",
      navigation: "التنقل",
      services: "الخدمات",
      contact: "اتصال",
      rights: "عدل إشهاد · جميع الحقوق محفوظة.",
    },
  },
} as const;

export type SiteCopy = (typeof copy)[Language];